### ISSUE TITLE
開發硬體選擇與功能討論

### ISSUE THREAD

**Issue by ckpiggy** [archspace/auto-feeder#5]
我向Sparkler請教硬體選擇，他建議我們在做prototype的時候用raspberry pi + camera開發，
最後再把code和外接裝置移植到海思的硬體上。原因有：

1. raspberry pi 的port比較多，性能比較好，方便debug
2. 在完成prototype之後可以輕易的把raspberry pi連接的硬體拔下來做移植，pi可以拿到下一個project使用
3. 他手上有一組pi + camera可以借我們用XD

另外他願意提供p2p連線的server side與client side的sdk給我們使用，我之後再把他提供的文件po上來

目前我還沒有想到馬達的選擇（camera 轉動與餵食都需要馬達）歡迎大家提供意見！

另外，我想順便討論一下我們規劃要開發的功能，大家可以在這個討論串說說自己想要的功能，最後由@visiontakulo來總結吧！

已提出功能
- 設定餵食時間
- 設定餵食量
- p2p live view和鏡頭旋轉 @ckpiggy
- 語音辨識，餵食裝置有聲控功能，用聲音來和裝置產生互動 @marktu555

**Comment by ckpiggy** [comment]
我先提一個 live view功能，可以用ipcam live view寵物的影像，並且讓鏡頭可以轉動。

**Comment by marktu555** [comment]
開發硬體選擇：
我覺得Sparkler的建議蠻好的。camera部分在prototype的階段，我建議可以找找看有沒有現成camera搭配馬達的開發模組，raspberry透過interface連接到該模組，可以驅動旋轉和得到影像的串流，來簡化live view功能實現的難度。

功能討論：
最近AI和語音辨識很夯，我提一個語音互動的功能，餵食裝置有聲控功能，用聲音來和裝置產生互動。

**Comment by alinyo** [comment]
語音辨識的話是不是要有一個MCU去做這件事?
不然就是丟到雲端或手機去辨識

**Comment by ckpiggy** [comment]
@alinyo  @marktu555 語音辨識的話aws alexa也許是一個選項
https://developer.amazon.com/alexa-voice-service

**Comment by alinyo** [comment]
恩 所以Alexa有提供SDK在raspberry pi 
https://github.com/alexa/alexa-avs-sample-app

**Comment by ckpiggy** [comment]
為了閱讀方便，我把大家提出的功能在一樓做個紀錄
另外我想請@visiontakulo 在12/4之前做個結論把這個討埨串close
我可以把功能規格寫進README.md

**Comment by ckpiggy** [comment]
昨天最後討論的結果：
本次規格會分三階段進行，第一階段時程為10週（本次專案PL @visiontakulo ），第二與第三階段是否實作要看之後的PL意願。每個階段實作的規格：
1. 手機與餵食器在LAN中互聯，用tcp/ip溝通，設定餵食時間與餵食量
2. 手機從外網連結回餵食器，實作餵食器彈射飼料功能
3. p2p連線live view，傳遞影像和聲音，鏡頭與餵食器轉動

如果各位在12/8之前沒有額外的事項要討論，那這次的規格就定案囉  我會在12/8發PR update README.md

**Comment by archspace** [comment]
依造討論結果
定案的話這一期的實作app控制的UI應該如<1>所示
有問題再討論修改

<1>與餵食器連線設定餵食時間與餵食量 (是否可以在非設定時間即時餵食  不是排程的餵食方式)
<2>控制彈射飼料的各種可能選項    如控制彈射角度 力道 數量等等UI
<3>單向或雙向影像呈現  控制鏡頭轉動  控制整機動作

我們會需要討論是否可以在排程時間以外即時連線做餵食動作

**Comment by ckpiggy** [comment]
結果更新在README
